### ISSUE TITLE
Plugin execution not covered by lifecycle configuration

### ISSUE THREAD

**Issue by khansquare** [okleine/nCoAP#29]
Hello!
Here I have to create a COAP listener so I am building this project in Eclipse Luna. But I'm facing some problems, have a look on the screenshot...
![coap](https://cloud.githubusercontent.com/assets/10682808/15609008/1547cdac-243b-11e6-9c5e-33d6c320d220.png)

Please help what I'm missing.

**Comment by boldt** [comment]
The Eclipse maven plugin does not know how to handle the **mycila-licence-plugin**. There are three solutions: 

For all: open "Quick fix":

![bildschirmfoto vom 2016-05-31 23 48 42](https://cloud.githubusercontent.com/assets/750793/15691841/669a1f4a-278b-11e6-9f21-d63e03604550.png)

followed by:

(1) "Discover new m2e connectors" 

Probably, this will not find a solution: Select **lifecycles** on the top and install **m2e-mycila-licence**

![bildschirmfoto vom 2016-05-31 23 49 26](https://cloud.githubusercontent.com/assets/750793/15691882/914d8326-278b-11e6-87d2-1b38cbb67c4e.png)

(2) "Mark goal format as ignored in Eclipse build in Eclipse preferences"

This ignores the message for a single project.

(1) "Permanently mark goal run in pom.xml as ignored in Eclipse build"

This ignores the message for all projects
