### ISSUE TITLE
Dependency - onejar-maven-plugin

### ISSUE THREAD

**Issue by rohling** [okleine/nCoAP#33]
Fail during the maven build :

Plugin org.dstovall:onejar-maven-plugin:1.4.4 or one of its dependencies could not be resolved: Failure to find org.dstovall:onejar-maven-plugin:jar:1.4.4 in https://repo.maven.apache.org/maven2 was cached ...

Dependency nCoAP-master:
<id>onejar-maven-plugin.googlecode.com</id>
            <url>http://onejar-maven-plugin.googlecode.com/svn/mavenrepo</url>

thanks,

**Comment by okleine** [comment]
It seems that the Googlecode-Repository is no longer online. Try to replace

`<groupId>org.dstovall</groupId>`

with

<groupId>com.jolira</groupId>. Please let me know if that worked for you.

(see [https://github.com/jolira/onejar-maven-plugin](https://github.com/jolira/onejar-maven-plugin))

**Comment by rohling** [comment]
Thank for  immediate return.... 

     But not ok...now:

[ERROR] Failed to execute goal com.jolira:onejar-maven-plugin:1.4.4:one-jar (default) on project ncoap-simple-client: Execution default of goal com.jolira:onejar-maven-plugin:1.4.4:one-jar failed: Unable to load the mojo 'one-jar' in the plugin 'com.jolira:onejar-maven-plugin:1.4.4'. A required class is missing: org.dstovall.OneJarMojo

thanks,

**Comment by okleine** [comment]
I just tried to reproduce your issue but I couldn't. When I change the group ID to `com.jolira` as I wrote above, the appropriate JAR is succesfully loaded into my local Maven repository at

`.m2/com/jolira/onejar-maven-plugin/1.4.4/onejar-maven-plugin-1.4.4.jar`

and this JAR file contains a class file `org.dstovall.OneJarMojo.class`. Furthermore, the Maven package-goal runs successfully...

**Comment by martinmine** [comment]
I was able to succesfully build the project by applying the changes proposed by @okleine and also remove from ./pom.xml:
```
    <pluginRepositories>
        <pluginRepository>
            <id>onejar-maven-plugin.googlecode.com</id>
            <url>http://onejar-maven-plugin.googlecode.com/svn/mavenrepo</url>
        </pluginRepository>
    </pluginRepositories>
```
Since the new plugin is in the official Maven repo and Google Code is no more. I'll submit a PR for this with my changes.

**Comment by jamesgarriss** [comment]
This issue still isn't fixed.  The POM has to be edited/corrected.

**Comment by martinmine** [comment]
@jamesgarriss then maybe submit that under a different pull request with your proposed changes? :)

**Comment by DarshanMurthy** [comment]
@jamesgarriss Is this issue fixed?
