### ISSUE TITLE
Send unsolicited messages from server to client?

### ISSUE THREAD

**Issue by martinscheffler** [okleine/nCoAP#38]
Hi, 
I would like to send messages from the server to the client. For example, the client registers itself with a POST message to some URI. Then the server keeps the address of that client around and periodically sends COAP messages to that client informing it of updates.
Is there a way to do this? Creating a CoapClient for each incoming connection does not seem to work, and I don't see any other way to do queries on the client.

Thank you!

**Comment by okleine** [comment]
Not sure if I got you right but I guess the observe option is your friend... (see [RFC 7641](https://tools.ietf.org/html/rfc7641)).
